# Generated by Django 5.0.4 on 2024-08-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='restuarant',
            new_name='restaurant',
        ),
    ]
